language: cpp
dist: xenial
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

script: 
  # Debug
  - cmake travis_qmake_gcc_cpp14_boost_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Release
  - cmake travis_qmake_gcc_cpp14_boost_test.pro
  - make release
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Test
  - cmake travis_qmake_gcc_cpp14_boost_test_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test_test
