language: cpp
dist: bionic
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

script: 
  - cmake .
  - make
  # Tests
  - ./travis_qmake_gcc_cpp14_boost_test
  - ./travis_qmake_gcc_cpp14_boost_test_test
